/** Digital Human Engine — shared types (Phase G). */

export const SYSTEM_IDS = [
  'skeletal', 'muscular', 'nervous', 'endocrine', 'cardiovascular', 'respiratory', 'digestive',
  'urinary', 'reproductive', 'lymphatic', 'integumentary', 'connective', 'fascial', 'surface',
] as const;
export type SystemId = (typeof SYSTEM_IDS)[number];

export const SYSTEM_META: Record<SystemId, { name: string; color: string; order: number }> = {
  skeletal: { name: 'Skeletal', color: '#e8e2d2', order: 1 },
  muscular: { name: 'Muscular', color: '#b5443c', order: 2 },
  nervous: { name: 'Nervous', color: '#f2c14e', order: 3 },
  endocrine: { name: 'Endocrine', color: '#c77dff', order: 4 },
  cardiovascular: { name: 'Cardiovascular', color: '#d62839', order: 5 },
  respiratory: { name: 'Respiratory', color: '#f28482', order: 6 },
  digestive: { name: 'Digestive', color: '#e6a157', order: 7 },
  urinary: { name: 'Urinary', color: '#f4d35e', order: 8 },
  reproductive: { name: 'Reproductive', color: '#ee9b9b', order: 9 },
  lymphatic: { name: 'Lymphatic', color: '#8fd694', order: 10 },
  integumentary: { name: 'Integumentary', color: '#d9b99b', order: 11 },
  connective: { name: 'Connective tissue', color: '#cbd5e1', order: 12 },
  fascial: { name: 'Fascial layers', color: '#e2e8f0', order: 13 },
  surface: { name: 'Surface anatomy', color: '#94a3b8', order: 14 },
};

export type BodyId = 'male' | 'female';

/** One structure entry in a body manifest (generated by the asset pipeline). */
export interface ManifestStructure {
  id: string;
  fmaId?: string;
  name: string;
  latinName?: string;
  aliases?: string[];
  systems: SystemId[];
  region?: string;
  laterality?: 'none' | 'left' | 'right';
  centroid: [number, number, number];
  bounds: [number, number, number, number, number, number];
  /** LOD files, index = level (0 = full). Absent for procedural demo structures. */
  lods?: { url: string; bytes: number; triangles: number }[];
  /** Procedural stand-in used when no mesh asset is available (development / tests). */
  procedural?: ProceduralShape;
  /**
   * Where the geometry came from. `hra` is a real anatomical mesh; `procedural` is a
   * generated stand-in shown because no openly licensed mesh of this structure exists yet.
   * The interface tells the student which they are looking at.
   */
  provenance?: 'hra' | 'bp3d' | 'procedural';
}

export type ProceduralShape =
  | { kind: 'box'; size: [number, number, number]; rotation?: [number, number, number] }
  | { kind: 'sphere'; radius: number; scale?: [number, number, number] }
  | { kind: 'capsule'; radius: number; length: number; rotation?: [number, number, number] }
  | { kind: 'tube'; radius: number; points: [number, number, number][] };

export interface BodyManifest {
  body: BodyId;
  version: string;
  pack: string;
  licence: string;
  attribution: string;
  structures: ManifestStructure[];
}

/** Everything needed to restore a view (FR-E9). Serialisable. */
export interface ViewState {
  body: BodyId;
  camera: { position: [number, number, number]; target: [number, number, number] };
  visibleSystems: SystemId[];
  hidden: string[];
  faded: string[];
  isolated: string[] | null;
  selected: string[];
  explode: number; // 0..1
  transparency: number; // 0..1 global
  clip: ClipState | null;
  compare: CompareState | null;
}

export interface ClipState {
  plane: 'axial' | 'coronal' | 'sagittal' | 'free';
  /** normal + constant (three.js Plane convention) */
  normal: [number, number, number];
  constant: number;
  enabled: boolean;
}

export interface CompareState {
  mode: 'split' | 'overlay';
  leftSystems: SystemId[];
  rightSystems: SystemId[];
}

export interface SavedView {
  id: string;
  name: string;
  createdAt: string;
  state: ViewState;
}

export interface Bookmark {
  structureId: string;
  note?: string;
  createdAt: string;
}
