/** Digital Human Engine — shared types (Phase G). */

export const SYSTEM_IDS = [
  'skeletal', 'muscular', 'nervous', 'endocrine', 'cardiovascular', 'respiratory', 'digestive',
  'urinary', 'reproductive', 'lymphatic', 'integumentary', 'connective', 'fascial', 'surface',
] as const;
export type SystemId = (typeof SYSTEM_IDS)[number];

export const SYSTEM_META: Record<SystemId, { name: string; color: string; order: number }> = {
  skeletal: { name: 'Skeletal', color: '#e8e2d2', order: 1 },
  muscular: { name: 'Muscular', color: '#b5443c', order: 2 },
  nervous: { name: 'Nervous', color: '#f2c14e', order: 3 },
  endocrine: { name: 'Endocrine', color: '#c77dff', order: 4 },
  cardiovascular: { name: 'Cardiovascular', color: '#d62839', order: 5 },
  respiratory: { name: 'Respiratory', color: '#f28482', order: 6 },
  digestive: { name: 'Digestive', color: '#e6a157', order: 7 },
  urinary: { name: 'Urinary', color: '#f4d35e', order: 8 },
  reproductive: { name: 'Reproductive', color: '#ee9b9b', order: 9 },
  lymphatic: { name: 'Lymphatic', color: '#8fd694', order: 10 },
  integumentary: { name: 'Integumentary', color: '#d9b99b', order: 11 },
  connective: { name: 'Connective tissue', color: '#cbd5e1', order: 12 },
  fascial: { name: 'Fascial layers', color: '#e2e8f0', order: 13 },
  surface: { name: 'Surface anatomy', color: '#94a3b8', order: 14 },
};

export type BodyId = 'male' | 'female';

/** One structure entry in a body manifest (generated by the asset pipeline). */
export interface ManifestStructure {
  id: string;
  fmaId?: string;
  name: string;
  latinName?: string;
  aliases?: string[];
  systems: SystemId[];
  region?: string;
  laterality?: 'none' | 'left' | 'right';
  centroid: [number, number, number];
  bounds: [number, number, number, number, number, number];
  /** LOD files, index = level (0 = full). Absent for procedural demo structures. */
  lods?: { url: string; bytes: number; triangles: number }[];
  /** Procedural stand-in used when no mesh asset is available (development / tests). */
  procedural?: ProceduralShape;
  /**
   * Where the geometry came from. `hra` is a real anatomical mesh; `procedural` is a
   * generated stand-in shown because no openly licensed mesh of this structure exists yet.
   * The interface tells the student which they are looking at.
   */
  provenance?: Provenance;
  /** Detail-pack membership: the id of the lazy-loaded bundle that carries this mesh. */
  group?: string;
  /** Anatomical kind, e.g. `bone`, `artery`, `nerve`, `ligament`. Used for counts and colour. */
  category?: string;
  /**
   * Depth in the skin-to-bone peel-away stack: 0 epidermis/skin, 1 dermis, 2 hypodermis/fat,
   * 3 deep fascia, 4 superficial muscle, 5 deep muscle, 6 skeleton and joints. Absent for
   * structures that are not part of the stack (viscera, vessels, nerves).
   */
  layer?: number;
  /** Location of this structure's mesh inside its detail group file (see packed.ts). */
  packed?: { o: number; vb: number; ib: number; nv: number; ni: number };
  /** Which open dataset the mesh came from, with its licence, for per-structure attribution. */
  source?: { name: string; licence: string };
}

/**
 * `hra` and `bp3d` and `zanatomy` are real anatomical meshes. `generated` is a schematic shape
 * derived from a real surface (the dermis and hypodermis shells), shown only where a layer
 * control asks for it and always labelled. `procedural` is a hand-made stand-in.
 */
export type Provenance = 'hra' | 'bp3d' | 'zanatomy' | 'generated' | 'procedural';

/** True for provenance values that are real, openly licensed anatomical geometry. */
export function isRealAnatomy(p: Provenance | undefined): boolean {
  return p === 'hra' || p === 'bp3d' || p === 'zanatomy';
}

export type ProceduralShape =
  | { kind: 'box'; size: [number, number, number]; rotation?: [number, number, number] }
  | { kind: 'sphere'; radius: number; scale?: [number, number, number] }
  | { kind: 'capsule'; radius: number; length: number; rotation?: [number, number, number] }
  | { kind: 'tube'; radius: number; points: [number, number, number][] };

export interface BodyManifest {
  body: BodyId;
  version: string;
  pack: string;
  licence: string;
  attribution: string;
  /** Detail-pack bundles (lazy loaded); absent in the core pack. */
  groups?: DetailGroup[];
  structures: ManifestStructure[];
}

export interface DetailGroup {
  id: string;
  title: string;
  description?: string;
  url: string;
  bytes: number;
  count: number;
  /** Core structures this group draws in more detail; hidden while the group is shown. */
  replaces?: string[];
  /** Loaded automatically once the manifest is known (small upgrades to stand-ins). */
  auto?: boolean;
}

/** Everything needed to restore a view (FR-E9). Serialisable. */
export interface ViewState {
  body: BodyId;
  camera: { position: [number, number, number]; target: [number, number, number] };
  visibleSystems: SystemId[];
  hidden: string[];
  faded: string[];
  isolated: string[] | null;
  selected: string[];
  explode: number; // 0..1
  transparency: number; // 0..1 global
  clip: ClipState | null;
  compare: CompareState | null;
  /** Detail-pack groups switched on (lazy loaded). Absent in views saved before detail packs. */
  groups?: string[];
  /** Peel-away depth, 0 (nothing peeled) to 6 (only the skeleton left). */
  peel?: number;
}

export interface ClipState {
  plane: 'axial' | 'coronal' | 'sagittal' | 'free';
  /** normal + constant (three.js Plane convention) */
  normal: [number, number, number];
  constant: number;
  enabled: boolean;
}

export interface CompareState {
  mode: 'split' | 'overlay';
  leftSystems: SystemId[];
  rightSystems: SystemId[];
}

export interface SavedView {
  id: string;
  name: string;
  createdAt: string;
  state: ViewState;
}

export interface Bookmark {
  structureId: string;
  note?: string;
  createdAt: string;
}
