/**
 * Adds the `schematic` group (generated stand-ins) to the anatomy-v2 pack of each body.
 *
 *   npm run assets:build:schematic     (runs after assets:build:v2; safe to run repeatedly)
 *
 * Every structure is provenance `generated`, category `schematic …`, and named "(schematic)".
 * None counts as real anatomy. See scripts/assets/schematic/generate.ts for how each is placed.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { bodyManifest } from '../../src/engine/manifest';
import { generate, SCHEMATIC_CATEGORIES } from './schematic/generate';
import { openBody } from './schematic/io';
import { boundsOfPiece, encodePiece, MeshoptEncoder } from './schematic/encode';
import { signedVolume } from './schematic/geom';

const ROOT = process.cwd();
const GROUP = 'schematic';
const NOTE = ' Schematic stand-ins (group "schematic") are generated by this project from the positions of real neighbouring structures; they are indicative only, are not scans or measured anatomy, and are never counted as real anatomy.';

async function main() {
  await MeshoptEncoder.ready;
  const report = JSON.parse(readFileSync(`${ROOT}/public/assets/anatomy-v2/build-report.json`, 'utf8'));
  for (const body of ['male', 'female'] as const) {
    const file = `${ROOT}/public/assets/anatomy-v2/${body}.manifest.json`;
    const manifest = JSON.parse(readFileSync(file, 'utf8'));
    // Idempotent: drop any earlier schematic group before adding it again.
    manifest.structures = manifest.structures.filter((s: { group?: string }) => s.group !== GROUP);
    manifest.groups = manifest.groups.filter((g: { id: string }) => g.id !== GROUP);
    manifest.attribution = String(manifest.attribution).replace(NOTE, '') + NOTE;
    writeFileSync(file, JSON.stringify(manifest));

    const b = await openBody(ROOT, body);
    const items = await generate(b, body);
    const existing = new Set<string>([...b.detail.structures.map((s) => s.id).filter((i) => !i.startsWith('x-')), ...b.core.structures.map((s) => s.id)]);
    const chunks: Uint8Array[] = []; let size = 0;
    const structures = [];
    for (const it of items) {
      if (existing.has(it.id)) throw new Error(`${body}: id ${it.id} already exists`);
      existing.add(it.id);
      if (!(it.mesh.indices.length >= 9)) throw new Error(`${it.id}: empty mesh`);
      if (SCHEMATIC_CATEGORIES.indexOf(it.category) < 0) throw new Error(`${it.id}: bad category`);
      for (const x of it.mesh.positions) if (!Number.isFinite(x)) throw new Error(`${it.id}: non-finite position`);
      if (it.category !== "schematic tooth" && signedVolume(it.mesh) <= 0) { console.error(it.id, signedVolume(it.mesh), it.mesh.positions.length / 3); throw new Error(`${it.id}: inverted or degenerate mesh`); }
      const { min, max } = boundsOfPiece(it.mesh);
      const enc = encodePiece(it.mesh, min, max);
      const ref = { o: size, vb: enc.vb.byteLength, ib: enc.ib.byteLength, nv: enc.nv, ni: enc.ni };
      chunks.push(enc.vb, enc.ib); size += enc.vb.byteLength + enc.ib.byteLength;
      const centroid = [0, 1, 2].map((k) => +((min[k]! + max[k]!) / 2).toFixed(5));
      structures.push({
        id: it.id, name: it.name, ...(it.aliases?.length ? { aliases: it.aliases } : {}), systems: it.systems, region: it.region, laterality: it.side,
        centroid, bounds: [...min, ...max].map((x) => +x.toFixed(5)),
        provenance: 'generated', group: GROUP, category: it.category,
        source: { name: 'Generated schematic stand-in (this project), placed from real neighbouring structures; not a scan, not measured anatomy', licence: 'CC-BY-SA-4.0' },
        packed: ref,
      });
    }
    const blob = Buffer.concat(chunks);
    const outFile = `group-${GROUP}.bin`;
    writeFileSync(path.join(ROOT, 'public/assets/anatomy-v2', body, outFile), blob);
    manifest.groups.push({
      id: GROUP, title: 'Schematic stand-ins (generated, not real anatomy)',
      description: 'Spinal nerves C1–Co1, cervical, lumbar and sacral plexuses, autonomic plexuses and ganglia, vagus, phrenic and splanchnic branches, third molars, small vessel branches, joint capsules and cartilage, sutures, and gap-fill placeholders (metopic suture, umbilical remnants, pleural cavities, fibrous pericardium, peritoneal sheets, nipples, and a representative inset of skin appendages). Drawn in violet from the positions of real structures; indicative courses only.',
      url: `/assets/anatomy-v2/${body}/${outFile}`, bytes: blob.byteLength, count: structures.length,
    });
    manifest.structures.push(...structures);
    bodyManifest.parse(manifest);
    writeFileSync(file, JSON.stringify(manifest));
    const byCat: Record<string, number> = {};
    for (const s of structures) byCat[s.category] = (byCat[s.category] ?? 0) + 1;
    console.log(`${body}: +${structures.length} schematic stand-ins, ${(blob.byteLength / 1024).toFixed(0)} KB`, byCat);
    const r = report[body];
    if (r) {
      r.byGroup = { ...r.byGroup, [GROUP]: structures.length };
      r.groups = [...r.groups.filter((g: { id: string }) => g.id !== GROUP), { id: GROUP, bytes: blob.byteLength, count: structures.length }];
      r.structures = manifest.structures.length; r.bytes = manifest.groups.reduce((a: number, g: { bytes: number }) => a + g.bytes, 0);
    }
  }
  writeFileSync(`${ROOT}/public/assets/anatomy-v2/build-report.json`, JSON.stringify(report, null, 1));
}
main().catch((e) => { console.error(e); process.exit(1); });
