#!/usr/bin/env python3
"""Generate docs/gap-audit.md from the shipped manifests (core hra-v1 + detail anatomy-v2).

Only counts read from the manifests and the build report are stated as facts. Reference
figures (206 bones, 12 cranial nerve pairs, ...) are standard textbook values and are marked
as such; no reference total is given where none is agreed (e.g. named arteries).
"""
import json, re, collections, sys, os, importlib.util
ROOT = sys.argv[1] if len(sys.argv) > 1 else '.'
def load(p): return json.load(open(f'{ROOT}/{p}'))
rep = load('public/assets/anatomy-v2/build-report.json')
REAL = ('hra', 'bp3d', 'zanatomy', 'openear', 'iemap')
_sp = importlib.util.spec_from_file_location('gap_eval', os.path.join(os.path.dirname(os.path.abspath(__file__)), 'gap_eval.py'))
gap_eval = importlib.util.module_from_spec(_sp); _sp.loader.exec_module(gap_eval)
out = []
w = out.append

# ---- the 206-bone check ------------------------------------------------------------------
def bones_expected():
    E = []
    for side in ('Left', 'Right'):
        for b in ['parietal bone','temporal bone','maxilla','zygomatic bone','nasal bone','lacrimal bone','palatine bone','inferior nasal concha bone','malleus','incus','stapes','clavicle','scapula','humerus','radius','ulna','hip bone','femur','patella','tibia','fibula']:
            E.append(f'{side} {b}')
        for b in ['scaphoid bone','lunate bone','triquetrum bone','pisiform bone','trapezium bone','trapezoid bone','capitate bone','hamate bone']: E.append(f'{side} {b}')
        for b in ['calcaneus','talus','navicular bone','cuboid bone','medial cuneiform bone','intermediate cuneiform bone','lateral cuneiform bone']: E.append(f'{side} {b}')
        for n in ['first','second','third','fourth','fifth']:
            E += [f'{side} {n} metacarpal bone', f'{side} {n} metatarsal bone']
            for part in ['proximal','distal']+(['middle'] if n != 'first' else []):
                E += [f'{side} {part} phalanx of {n} finger of hand', f'{side} {part} phalanx of {n} finger of foot']
        for n in ['first','second','third','fourth','fifth','sixth','seventh','eighth','ninth','tenth','eleventh','twelfth']: E.append(f'{side} {n} rib')
    E += ['Frontal bone','Occipital bone','Sphenoid bone','Ethmoid bone','Vomer','Mandible','Hyoid bone','Sacrum','Coccyx','Manubrium of sternum','Body of sternum','Xiphoid process','Atlas (C1)','Axis (C2)']
    E += [f'Vertebra {r}{i}' for r, n in (('C',7),('T',12),('L',5)) for i in range(1, n+1) if not (r == 'C' and i < 3)]
    return E

def coverage(body):
    m = load(f'public/assets/anatomy-v2/{body}.manifest.json')['structures']
    names = {s['name'].lower() for s in m if s.get('category') == 'bone'}
    exp = bones_expected()
    missing = [e for e in exp if e.lower() not in names]
    # the standard count treats each phalanx of the hand/foot as one bone (2 x 14 each) - check the count itself
    return len(exp), missing, len([s for s in m if s.get('category') == 'bone'])

# ---- counts ------------------------------------------------------------------------------
def counts(body):
    core = load(f'public/assets/hra-v1/{body}.manifest.json')['structures']
    det = load(f'public/assets/anatomy-v2/{body}.manifest.json')['structures']
    up = {s['id'] for s in det if s['group'] == 'core-upgrades'}
    return core, det, up

w('# Gap audit — how complete is the model?\n')
w('_Generated by `scripts/assets/gap-audit.py` from the shipped manifests and the `assets:build:v2` build report. Re-run it after every pack rebuild: `python3 scripts/assets/gap-audit.py . > docs/gap-audit.md`._\n')
w('**Reading the numbers.** "Named structure" means one object in the manifest with an id, name, licence and provenance. It does not mean an independently verified reconstruction: the detail pack is Z-Anatomy geometry registered into each HRA body (see *Fit quality*). "Reference" figures are standard textbook values and are given only where there is an agreed total.\n')

w('## 1. Before and after\n')
rows = {}
for body in ('male', 'female'):
    core, det, up = counts(body)
    merged = [s for s in core if s['id'] not in up] + det
    rows[body] = dict(core=len(core), core_real=sum(1 for s in core if s.get('provenance') in REAL), after=len(merged),
        real=sum(1 for s in merged if s.get('provenance') in REAL),
        generated=sum(1 for s in merged if s.get('provenance') == 'generated'),
        schematic=sum(1 for s in merged if str(s.get('category', '')).startswith('schematic')),
        shells=sum(1 for s in merged if s.get('category') == 'skin layer' and s.get('provenance') == 'generated'),
        procedural=sum(1 for s in merged if s.get('provenance') == 'procedural'),
        ear=sum(1 for s in merged if s.get('provenance') in ('openear', 'iemap')))
# PREV = the pack as committed in 68c259c (the release before the anatomy-completeness QA round), recorded by hand from that build.
PREV = {'male': dict(after=3523, real=3164, generated=357, schematic=352, procedural=2), 'female': dict(after=3545, real=3182, generated=361, schematic=356, procedural=2)}
r = rows
w('| | Male: core only | Male: previous (68c259c) | Male: now | Female: core only | Female: previous (68c259c) | Female: now |\n|---|---:|---:|---:|---:|---:|---:|')
def line(label, key, corekey=None, prevkey=None):
    cm = r['male'][corekey] if corekey else 0; cf = r['female'][corekey] if corekey else 0
    w(f"| {label} | {cm} | {PREV['male'][prevkey or key]} | {r['male'][key]} | {cf} | {PREV['female'][prevkey or key]} | {r['female'][key]} |")
line('Structures in the atlas', 'after', 'core')
line('… real anatomy (HRA, BodyParts3D, Z-Anatomy, OpenEar, IE-Map)', 'real', 'core_real')
line('… generated (schematic stand-ins + skin-layer shells)', 'generated')
line('… of which schematic stand-ins (nerves, vessels, capsules, eye, cartilage, conduction, …)', 'schematic')
line('… procedural landmarks (points, not meshes)', 'procedural')
w(f"\nReal inner-ear and ear-canal structures in the pack (OpenEar + IE-Map): **{r['male']['ear']}** male / **{r['female']['ear']}** female. Net change in real anatomy since 68c259c: **+{r['male']['real']-PREV['male']['real']}** male / **+{r['female']['real']-PREV['female']['real']}** female; schematic stand-ins **+{r['male']['schematic']-PREV['male']['schematic']}** / **+{r['female']['schematic']-PREV['female']['schematic']}**. Generated structures are flagged `generated` in the manifest, violet with a badge in the UI, and are never counted as real anatomy.\n")

w('## 2. Detail pack by category (after)\n')
for body in ('male', 'female'):
    core, det, up = counts(body)
    c = collections.Counter(s['category'] for s in det)
    w(f'**{body.capitalize()}** — ' + ', '.join(f'{k}: {v}' for k, v in sorted(c.items(), key=lambda kv: -kv[1])) + '\n')
w('Core (`hra-v1`) is unchanged: 57 male / 59 female structures. Detail structures that share an id with a core stand-in replace it.\n')

# ---- explicit checklist by system ---------------------------------------------------------------
w('## 2b. Checklist by system (present / schematic / missing)\n')
w('A hand-picked checklist of named structures a gross-anatomy atlas is expected to show (`scripts/assets/gap-checklist.py`; not an official standard, see the Terminologia Anatomica figure below for the full list). **Present** = a real mesh exists (HRA, BodyParts3D, Z-Anatomy, OpenEar, IE-Map). **Schematic** = only a generated, labelled stand-in exists (not real). **Missing** = neither. Sex-specific entries are not counted on the other body.\n')
EV = {b: gap_eval.evaluate(ROOT, b) for b in ('male', 'female')}
w('| System | Checklist items | Male present | Male schematic | Male missing | Female present | Female schematic | Female missing |\n|---|---:|---:|---:|---:|---:|---:|---:|')
tot = {b: [0, 0, 0] for b in EV}
for system in gap_eval.ck.CHECK:
    cells = []
    n_items = len(gap_eval.ck.CHECK[system])
    for b in ('male', 'female'):
        rws = EV[b][system]
        c = [sum(1 for x in rws if x[2] == k) for k in ('real', 'schematic', 'missing')]
        for k in range(3): tot[b][k] += c[k]
        cells += c
    w(f'| {system} | {n_items} | ' + ' | '.join(map(str, cells)) + ' |')
w(f"| **Total** | | {tot['male'][0]} | {tot['male'][1]} | {tot['male'][2]} | {tot['female'][0]} | {tot['female'][1]} | {tot['female'][2]} |\n")
w('### Truly remaining items (missing on at least one body)\n')
w('| System | Item | Missing on | Why |\n|---|---|---|---|')
nrem = 0
for system in gap_eval.ck.CHECK:
    for k, (label, spec_s) in enumerate(gap_eval.ck.CHECK[system]):
        on = [b for b in ('male', 'female') if EV[b][system][k][2] == 'missing']
        if on:
            nrem += 1
            w(f"| {system} | {label} | {', '.join(on)} | {gap_eval.ck.REASON.get(label, 'no open mesh and not drawn')} |")
if not nrem: w('| | none | | |')
w('')
w('### Items present only as a schematic stand-in (not real)\n')
w('| System | Item | Bodies |\n|---|---|---|')
for system in gap_eval.ck.CHECK:
    for k, (label, spec_s) in enumerate(gap_eval.ck.CHECK[system]):
        on = [b for b in ('male', 'female') if EV[b][system][k][2] == 'schematic']
        if on: w(f"| {system} | {label} | {', '.join(on)} |")
w('')
w('### Full checklist with status\n')
w('<details><summary>Every checklist item (male / female status)</summary>\n')
w('| System | Item | Male | Female |\n|---|---|---|---|')
for system in gap_eval.ck.CHECK:
    for k, (label, spec_s) in enumerate(gap_eval.ck.CHECK[system]):
        w(f"| {system} | {label} | {EV['male'][system][k][2]} | {EV['female'][system][k][2]} |")
w('\n</details>\n')

# ---- Terminologia Anatomica name-match (indicative) ---------------------------------------------------
TA2 = os.environ.get('TA2_CSV', '/workspace/sources/zanat/TA2.csv')
w('### Terminologia Anatomica (TA2) name match, indicative\n')
if os.path.exists(TA2):
    CH = [(366,'Skeleton: bones',1514),(1515,'Joints and ligaments',1974),(1975,'Muscles (and tendons)',2772),(2773,'Digestive system',3132),(3133,'Respiratory system',3356),(3357,'Urinary system',3467),(3468,'Genital systems',3851),(3852,'Endocrine glands',3890),(3891,'Cardiovascular: blood vessels and heart',5148),(5149,'Lymphoid system',5362),(5363,'Central nervous system',6128),(6129,'Peripheral nervous system',6729),(6730,'Sense organs (eye, ear, ...)',7040),(7041,'Integument (skin)',7134)]
    norm = lambda t: re.sub(r'\s+', ' ', re.sub(r'[^a-z0-9 ]', ' ', re.sub(r'\b(left|right|dexter|sinister)\b', '', t.lower()).replace('ae ', 'a ').replace('ii', 'i'))).strip()
    trows = []
    for ln in open(TA2, encoding='utf-8-sig').read().split('\n')[1:]:
        c = ln.strip().strip('"').split(';')
        if len(c) >= 3 and c[0].isdigit(): trows.append((int(c[0]), c[1].strip(), c[2].strip()))
    def chap(i):
        for a, n, b in CH:
            if a <= i <= b: return n
    def names(body):
        st = load(f'public/assets/anatomy-v2/{body}.manifest.json')['structures'] + load(f'public/assets/hra-v1/{body}.manifest.json')['structures']
        real, sch = set(), set()
        for x in st:
            tgt = sch if str(x.get('category', '')).startswith('schematic') or x.get('provenance') in ('generated', 'procedural') else real
            for k in [x['name'], x.get('latinName', '')] + x.get('aliases', []):
                n = norm(re.sub(r'\(schematic\)|\(schematic shell\)', '', k or ''))
                if n: tgt.add(n); tgt.add(re.sub(r's\b', '', n))
        return real, sch
    res = {}
    for body in ('male', 'female'):
        real, sch = names(body); cnt = collections.defaultdict(lambda: [0, 0, 0]); seen = set()
        for i, e, l in trows:
            c = chap(i)
            if not c: continue
            ne, nl = norm(e), norm(l)
            if ne in seen: continue
            seen.add(ne)
            ks = [ne, re.sub(r's\b', '', ne), nl, re.sub(r's\b', '', nl)]
            if any(k in real for k in ks): cnt[c][0] += 1
            elif any(k in sch for k in ks): cnt[c][1] += 1
            else: cnt[c][2] += 1
        res[body] = cnt
    w('Exact-name match of the unique English TA2 terms (Z-Anatomy\'s copy, **used only as a lookup list, not redistributed**) against structure names, Latin names and aliases. Many TA2 terms are abstract, regional or surface-anatomy terms that are not separate meshes in any source, so this is **an indicative lower bound on coverage, not a completeness score**.\n')
    w('| TA2 chapter | Terms | Male real | Male schematic | Male no match | Female real | Female schematic | Female no match |\n|---|---:|---:|---:|---:|---:|---:|---:|')
    T = [0] * 7
    for a, n, b in CH:
        m, f = res['male'][n], res['female'][n]; row = [sum(m), *m, *f]
        for k in range(7): T[k] += row[k]
        w(f'| {n} | ' + ' | '.join(map(str, row)) + ' |')
    w('| **All chapters** | ' + ' | '.join(f'**{x}**' for x in T) + ' |\n')
else:
    w('_TA2 term list not available in this environment (set `TA2_CSV`); skipped._\n')

w('## 3. By system\n')
w('Present = real mesh in the shipped packs (the system table also includes the generated schematic stand-ins listed in 3.7). Stand-in = generated, labelled. Missing = not shipped, with the reason.\n')
def sysline(body):
    core, det, up = counts(body)
    merged = [s for s in core if s['id'] not in up] + det
    c = collections.Counter(); 
    for s in merged: c[s['systems'][0]] += 1
    return c
cm, cf = sysline('male'), sysline('female')
w('| System (primary tag) | Male | Female |\n|---|---:|---:|')
for k in sorted(set(cm) | set(cf), key=lambda k: -cm.get(k, 0)): w(f'| {k} | {cm.get(k,0)} | {cf.get(k,0)} |')
w('')

def cat(body, *cs):
    return [s for s in counts(body)[1] if s.get('category') in cs]

# Skeleton
n, missing, have = coverage('male')
nf, missingf, havef = coverage('female')
w('### 3.1 Skeleton\n')
w(f'- Reference: 206 named bones in the adult skeleton (standard count). The expected list built in the audit script has {n} entries: the 206 count treats the sternum as one bone, the list splits it into manubrium, body and xiphoid process (+2). The 206 includes the six ear ossicles.')
w(f'- Present in the male pack: **{n - len(missing)} of {n}** expected bones ({have} bone objects; the extra {have-(n-len(missing))} are 2 foot sesamoid groups, 6 ethmoid air-cell objects and 2 sinus objects). Female: **{nf - len(missingf)} of {nf}** ({havef} bone objects).')
if missing or missingf: w(f'- Missing: {sorted(set(missing+missingf))}')
else: w('- Missing: none of the 206.')
w('- Not modelled as separate bones: the patellar/hand sesamoids other than the foot groups; the fused sacral and coccygeal segments (sacrum and coccyx are single bones, as in the count); accessory ossicles and sutural bones (variants, not part of the 206).')
w(f"- Teeth: {len(cat('male','tooth'))} real teeth of the 32 permanent teeth. The four third molars are not in any source scan; they are added as **generated schematic** copies of the second molars (section 3.7) and are not counted as real.")
w('- Cartilages: ' + str(len(cat('male','cartilage'))) + ' (costal, laryngeal, nasal, articular and others present in Z-Anatomy).')
w(f"- Joints, capsules and discs: ligaments {len(cat('male','ligament'))}, capsules {len(cat('male','capsule'))}, intervertebral and other discs {len(cat('male','disc'))}.\n")

w('### 3.2 Muscular system, tendons, fascia, bursae\n')
w(f"- Muscles: {len(cat('male','muscle'))} (male) / {len(cat('female','muscle'))} (female), tendons {len(cat('male','tendon'))}, tendon sheaths {len(cat('male','tendon sheath'))}, bursae {len(cat('male','bursa'))}, fascia {len(cat('male','fascia'))}, membranes {len(cat('male','membrane'))}.")
w('- Reference: textbooks commonly quote 600–650 skeletal muscles depending on how they are split; there is no single agreed total, so no percentage is claimed.')
w('- Muscle attachment markers in Z-Anatomy (703 male objects) are annotations, not structures, and are excluded.\n')

w('### 3.3 Vessels\n')
w(f"- Arteries: {len(cat('male','artery'))} male / {len(cat('female','artery'))} female. Veins: {len(cat('male','vein'))} / {len(cat('female','vein'))}. Lymph nodes: {len(cat('male','lymph node'))} / {len(cat('female','lymph node'))}, lymphoid organs {len(cat('male','lymphoid'))}, ducts {len(cat('male','duct'))}.")
w('- Named trunk vessels are present (ascending, thoracic and abdominal aorta, superior and inferior vena cava, the cerebral, coronary, limb and visceral branches Z-Anatomy names). The great vessels of the heart are in the core pack from the HRA.')
w('- No agreed reference total for named vessels exists, so none is claimed. Named vessels that Z-Anatomy does not model (many small muscular, cutaneous and perforating branches, most named venous tributaries at the fourth order and below) are missing.')
w('- Capillaries, microvasculature and lymphatic capillaries are out of scope for a gross-anatomy model.\n')

w('### 3.4 Nervous system\n')
w(f"- Nerves {len(cat('male','nerve'))}, plexuses {len(cat('male','plexus'))}, ganglia {len(cat('male','ganglion'))}, meninges {len(cat('male','meninges'))}; brain regions {len(cat('male','brain region'))} (Allen Human Reference Atlas, via HRA).")
w('- **All 12 cranial nerve pairs are present** (I–XII, left and right), checked by the test suite.')
w('- Reference: 31 pairs of spinal nerves. The scans provide the anterior and posterior roots, the cauda equina, the intercostal nerves, the sympathetic trunk, the brachial plexus (roots, trunks, divisions, cords) and the named peripheral nerves of the limbs. **No scan provides the 31 individually named pairs**, so C1–C8, T1–T12, L1–L5, S1–S5 and Co1 (both sides) are supplied as generated schematic tubes (section 3.7), together with the cervical, lumbar and sacral plexuses and the autonomic plexuses. Cutaneous and small nerves of the head, neck and limbs, the cranial ganglia and cardiac conduction tissue are added as schematic stand-ins (section 3.7). Still missing: most other cutaneous branches, dermatomal rami as separate objects, and the fine autonomic plexuses on individual organs.')
w('- Brain and spinal-cord internal structures from Z-Anatomy (239 male objects) are **excluded**: their provenance inside Z-Anatomy is UW Brainder, which could not be verified. The brain is shown from the HRA/Allen regions instead.')
w('- The spinal cord is the HRA spinal cord (real), replacing the earlier stand-in.\n')

w('### 3.5 Organs, glands, other systems\n')
w(f"- Organ parts from the HRA and Z-Anatomy: digestive {len(cat('male','digestive part'))}, urinary {len(cat('male','urinary part'))}, reproductive {len(cat('male','reproductive part'))} (male) / {len(cat('female','reproductive part'))} (female), heart parts {len(cat('male','heart part'))}, valves {len(cat('male','valve'))}, liver parts {len(cat('male','liver part'))}, bronchi {len(cat('male','bronchus'))}, larynx {len(cat('male','larynx'))}, eye structures {len(cat('male','eye structure'))}, glands {len(cat('male','gland'))}, endocrine {len(cat('male','endocrine'))}.")
w('- Coronary branches, cardiac veins, hepatic/portal branches and rectal, sigmoid and colic vessels that Z-Anatomy lacks come from the HRA 3D Reference Object Library (CC BY 4.0) through an allow-list.')
w('- Lungs and thyroid are now real meshes (Z-Anatomy lobes; the thyroid gland).')
w('- **Inner ear and ear canal are now real** (26 structures per body): scala tympani, scala vestibuli, round window and external acoustic meatus from **OpenEar** (CC BY 4.0, Zenodo 1473724, specimen ALPHA), and cochlear duct, three semicircular ducts, three ampullae, utricle and saccule from **IE-Map** (CC BY 4.0, Zenodo 10625570). They are registered onto each body\'s real ossicles (ossicle RMS about 0.5-0.6 mm, size kept). The labyrinth is a template from another subject fitted with about 1 mm residual, and the left ear is the right ear mirrored, not a separate scan.')
w('- Still excluded: the Z-Anatomy **inner ear** (CC BY-NC-SA 4.0, Univ. of Dundee) and the **Z-Anatomy kidney** (CC BY-NC 4.0). The HRA kidney (CC BY 4.0) is used instead.')
w('- Heart chambers and valves from Z-Anatomy are skipped so that everything registers to the HRA heart in the core pack.')
w('- Mammary gland (female) is the HRA mammary model. The thoracic duct is a schematic stand-in.\n')

w('### 3.6 Skin and layers\n')
w('| Layer (peel-away) | Source | Status |\n|---|---|---|\n| 0 Skin surface | HRA skin (core) | real |\n| 1 Epidermis (0.8 mm) | HRA skin offset inward | **generated, schematic** |\n| 1 Papillary dermis (2 mm) | HRA skin offset inward | **generated, schematic** |\n| 1 Reticular dermis (4 mm) | HRA skin offset inward | **generated, schematic** |\n| 2 Membranous layer of subcutaneous tissue (9 mm) | HRA skin offset inward | **generated, schematic** |\n| 2 Hypodermis / subcutaneous fat (14 mm) | HRA skin offset inward, plus real HRA subcutaneous abdominal fat patches | shell **generated, schematic**; fat patches real |\n| 3 Deep fascia | Z-Anatomy fasciae | real, fitted |\n| 4 Superficial muscles | Z-Anatomy / BodyParts3D | real, fitted |\n| 5 Deep muscles, tendon sheaths, bursae | Z-Anatomy | real, fitted |\n| 6 Skeleton, cartilage, joints | Z-Anatomy | real, fitted |\n')
w('- No open, commercially usable whole-body mesh of epidermis, dermis or hypodermis was found (searched again this round). The five shells are uniform-thickness offsets of the skin surface, labelled "(schematic shell)" in the UI with provenance `generated`; they are excluded from every "real anatomy" count and real regional thicknesses vary.')
w('- Not modelled: epidermal sub-layers (stratum corneum … basale), sweat and sebaceous glands, hair follicles, arrector pili, dermal nerve endings and capillary loops (microscopic; no open mesh). Nails (8) and hair objects (eyebrows, eyelashes, pubic hair; scalp hair excluded because it does not fit either skull) are present and real.\n')

sch = {b: [x for x in counts(b)[1] if str(x.get('category','')).startswith('schematic')] for b in ('male','female')}
w('### 3.7 Schematic stand-ins (generated, not real anatomy)\n')
for b in ('male','female'):
    c = collections.Counter(x['category'] for x in sch[b])
    w(f"- {b.capitalize()}: **{len(sch[b])}** generated structures — " + ', '.join(f"{k.replace('schematic ','')}: {v}" for k, v in sorted(c.items())) + '.')
w('- What they are: 62 spinal nerves (31 pairs); cervical, lumbar and sacral plexuses; sympathetic ganglia and trunk segments; splanchnic, hypogastric and pelvic splanchnic nerves; autonomic plexuses; about 25 cutaneous and small nerves (supra-orbital, supratrochlear, infra-orbital, auriculotemporal, great auricular, lesser/greater/third occipital, supraclavicular, intercostobrachial, sural and others); cranial ganglia (trigeminal, ciliary, pterygopalatine, otic, submandibular, geniculate); about 40 small arteries and veins (superior thyroid, lingual, bronchial, gastric, jejunal, ileal, anterior interosseous, princeps pollicis, labyrinthine, anterior choroidal, internal and great cerebral veins, and others); the thoracic duct; cardiac conduction (SA node, AV node, AV bundle, bundle branches); eyelids, tarsal plates and periorbita; tracheal cartilages, cuneiform and auricular cartilages, vestibular and vocal folds; tensor tympani and stapedius; sagittal, coronal and lambdoid sutures; 46 facet-joint capsules plus atlanto-occipital, atlanto-axial, sacro-iliac and talocrural capsules; quadriceps, distal biceps and triceps tendons; four third molars; the dorsal nerve of the penis or clitoris.')
w('- How they are made: `scripts/assets/schematic/generate.ts` and `extra.ts` build tubes, blobs, thin shells and sleeves, positioned from the registered vertebrae, discs, spinal cord, sacrum, rib cage, skull bones, existing nerves, vessels and organs of the same body. Courses are indicative and have not been checked by an anatomist.')
w('- How they are flagged: provenance `generated`, category `schematic …`, name ends "(schematic)", violet colour, a badge on the structure card, the "Schematic" tag in search hits, their own lazy group, and they are excluded from every real-anatomy count.\n')

w('## 4. What Z-Anatomy contains that is not shipped\n')
w('From `build-report.json` (male; female is similar). These are counts of source objects, by reason:\n')
w('| Reason | Objects |\n|---|---:|')
for k, v in sorted(rep['male']['skipped'].items(), key=lambda kv: -kv[1]): w(f'| {k} | {v} |')
w('')
w('## 5. Fit quality (read before calling this "accurate")\n')
w('- The core HRA organs are in one reference frame, so they line up. The Z-Anatomy geometry comes from a different (male) subject and is registered into each HRA body by a global scale and translation, a spine-following displacement, and a per-leg similarity transform (`scripts/assets/extract/register.py`). Residuals: spine ≈ 4 mm RMS; ossicles/inner ear ≈ 0.5-1 mm (separate registration onto the ossicles); leg landmarks 24–40 mm (male), 8–18 mm (female).')
w('- The **female** body uses the male-derived Z-Anatomy skeleton, muscles, nerves and vessels fitted to the female HRA frame. Sex-specific organs come from the female HRA.')
w('- Fine structures (small nerves, digital vessels, the inner ear) may not sit exactly inside the soft tissue of the fitted body. This has been checked visually only in software-rendered headless Chrome, not by an anatomist.\n')
print('\n'.join(out))
