#!/usr/bin/env python3
"""Generate docs/gap-audit.md from the shipped manifests (core hra-v1 + detail anatomy-v2).

Only counts read from the manifests and the build report are stated as facts. Reference
figures (206 bones, 12 cranial nerve pairs, ...) are standard textbook values and are marked
as such; no reference total is given where none is agreed (e.g. named arteries).
"""
import json, re, collections, sys
ROOT = sys.argv[1] if len(sys.argv) > 1 else '.'
def load(p): return json.load(open(f'{ROOT}/{p}'))
rep = load('public/assets/anatomy-v2/build-report.json')
out = []
w = out.append

# ---- the 206-bone check ------------------------------------------------------------------
def bones_expected():
    E = []
    for side in ('Left', 'Right'):
        for b in ['parietal bone','temporal bone','maxilla','zygomatic bone','nasal bone','lacrimal bone','palatine bone','inferior nasal concha bone','malleus','incus','stapes','clavicle','scapula','humerus','radius','ulna','hip bone','femur','patella','tibia','fibula']:
            E.append(f'{side} {b}')
        for b in ['scaphoid bone','lunate bone','triquetrum bone','pisiform bone','trapezium bone','trapezoid bone','capitate bone','hamate bone']: E.append(f'{side} {b}')
        for b in ['calcaneus','talus','navicular bone','cuboid bone','medial cuneiform bone','intermediate cuneiform bone','lateral cuneiform bone']: E.append(f'{side} {b}')
        for n in ['first','second','third','fourth','fifth']:
            E += [f'{side} {n} metacarpal bone', f'{side} {n} metatarsal bone']
            for part in ['proximal','distal']+(['middle'] if n != 'first' else []):
                E += [f'{side} {part} phalanx of {n} finger of hand', f'{side} {part} phalanx of {n} finger of foot']
        for n in ['first','second','third','fourth','fifth','sixth','seventh','eighth','ninth','tenth','eleventh','twelfth']: E.append(f'{side} {n} rib')
    E += ['Frontal bone','Occipital bone','Sphenoid bone','Ethmoid bone','Vomer','Mandible','Hyoid bone','Sacrum','Coccyx','Manubrium of sternum','Body of sternum','Xiphoid process','Atlas (C1)','Axis (C2)']
    E += [f'Vertebra {r}{i}' for r, n in (('C',7),('T',12),('L',5)) for i in range(1, n+1) if not (r == 'C' and i < 3)]
    return E

def coverage(body):
    m = load(f'public/assets/anatomy-v2/{body}.manifest.json')['structures']
    names = {s['name'].lower() for s in m if s.get('category') == 'bone'}
    exp = bones_expected()
    missing = [e for e in exp if e.lower() not in names]
    # the standard count treats each phalanx of the hand/foot as one bone (2 x 14 each) - check the count itself
    return len(exp), missing, len([s for s in m if s.get('category') == 'bone'])

# ---- counts ------------------------------------------------------------------------------
def counts(body):
    core = load(f'public/assets/hra-v1/{body}.manifest.json')['structures']
    det = load(f'public/assets/anatomy-v2/{body}.manifest.json')['structures']
    up = {s['id'] for s in det if s['group'] == 'core-upgrades'}
    return core, det, up

w('# Gap audit — how complete is the model?\n')
w('_Generated by `scripts/assets/gap-audit.py` from the shipped manifests and the `assets:build:v2` build report. Re-run it after every pack rebuild: `python3 scripts/assets/gap-audit.py . > docs/gap-audit.md`._\n')
w('**Reading the numbers.** "Named structure" means one object in the manifest with an id, name, licence and provenance. It does not mean an independently verified reconstruction: the detail pack is Z-Anatomy geometry registered into each HRA body (see *Fit quality*). "Reference" figures are standard textbook values and are given only where there is an agreed total.\n')

w('## 1. Before and after\n')
w('| | Male before | Male after | Female before | Female after |\n|---|---:|---:|---:|---:|')
rows = {}
for body in ('male', 'female'):
    core, det, up = counts(body)
    real_before = sum(1 for s in core if s.get('provenance') in ('hra', 'bp3d'))
    merged = [s for s in core if s['id'] not in up] + det
    real_after = sum(1 for s in merged if s.get('provenance') in ('hra', 'bp3d', 'zanatomy'))
    rows[body] = dict(before=len(core), before_real=real_before, after=len(merged), after_real=real_after, generated=sum(1 for s in merged if s.get('provenance') == 'generated'), schematic=sum(1 for s in merged if str(s.get('category','')).startswith('schematic')), procedural=sum(1 for s in merged if s.get('provenance') == 'procedural'))
r = rows
w(f"| Structures in the atlas | {r['male']['before']} | {r['male']['after']} | {r['female']['before']} | {r['female']['after']} |")
w(f"| … of which real anatomy | {r['male']['before_real']} | {r['male']['after_real']} | {r['female']['before_real']} | {r['female']['after_real']} |")
w(f"| … generated, labelled schematic | 0 | {r['male']['generated']} | 0 | {r['female']['generated']} |")
w(f"| … of which schematic stand-ins (nerves, plexuses, ganglia, vessels, third molars) | 0 | {r['male']['schematic']} | 0 | {r['female']['schematic']} |")
w(f"| … procedural stand-ins | {r['male']['before']-r['male']['before_real']} | {r['male']['procedural']} | {r['female']['before']-r['female']['before_real']} | {r['female']['procedural']} |")
w('\nThe remaining procedural stand-ins are the `jugular-notch` and `umbilicus` landmarks (surface points, not meshes). The generated rows are the two skin shells plus the **schematic stand-ins** (group `schematic`, section 3.7): they are drawn by this project from the positions of real neighbouring structures, are flagged `generated` in the manifest and violet with a badge in the UI, and are never counted as real anatomy.\n')

w('## 2. Detail pack by category (after)\n')
for body in ('male', 'female'):
    core, det, up = counts(body)
    c = collections.Counter(s['category'] for s in det)
    w(f'**{body.capitalize()}** — ' + ', '.join(f'{k}: {v}' for k, v in sorted(c.items(), key=lambda kv: -kv[1])) + '\n')
w('Core (`hra-v1`) is unchanged: 57 male / 59 female structures. Detail structures that share an id with a core stand-in replace it.\n')

w('## 3. By system\n')
w('Present = real mesh in the shipped packs (the system table also includes the generated schematic stand-ins listed in 3.7). Stand-in = generated, labelled. Missing = not shipped, with the reason.\n')
def sysline(body):
    core, det, up = counts(body)
    merged = [s for s in core if s['id'] not in up] + det
    c = collections.Counter(); 
    for s in merged: c[s['systems'][0]] += 1
    return c
cm, cf = sysline('male'), sysline('female')
w('| System (primary tag) | Male | Female |\n|---|---:|---:|')
for k in sorted(set(cm) | set(cf), key=lambda k: -cm.get(k, 0)): w(f'| {k} | {cm.get(k,0)} | {cf.get(k,0)} |')
w('')

def cat(body, *cs):
    return [s for s in counts(body)[1] if s.get('category') in cs]

# Skeleton
n, missing, have = coverage('male')
nf, missingf, havef = coverage('female')
w('### 3.1 Skeleton\n')
w(f'- Reference: 206 named bones in the adult skeleton (standard count). The expected list built in the audit script has {n} entries: the 206 count treats the sternum as one bone, the list splits it into manubrium, body and xiphoid process (+2). The 206 includes the six ear ossicles.')
w(f'- Present in the male pack: **{n - len(missing)} of {n}** expected bones ({have} bone objects; the extra {have-(n-len(missing))} are 2 foot sesamoid groups, 6 ethmoid air-cell objects and 2 sinus objects). Female: **{nf - len(missingf)} of {nf}** ({havef} bone objects).')
if missing or missingf: w(f'- Missing: {sorted(set(missing+missingf))}')
else: w('- Missing: none of the 206.')
w('- Not modelled as separate bones: the patellar/hand sesamoids other than the foot groups; the fused sacral and coccygeal segments (sacrum and coccyx are single bones, as in the count); accessory ossicles and sutural bones (variants, not part of the 206).')
w(f"- Teeth: {len(cat('male','tooth'))} real teeth of the 32 permanent teeth. The four third molars are not in any source scan; they are added as **generated schematic** copies of the second molars (section 3.7) and are not counted as real.")
w('- Cartilages: ' + str(len(cat('male','cartilage'))) + ' (costal, laryngeal, nasal, articular and others present in Z-Anatomy).')
w(f"- Joints, capsules and discs: ligaments {len(cat('male','ligament'))}, capsules {len(cat('male','capsule'))}, intervertebral and other discs {len(cat('male','disc'))}.\n")

w('### 3.2 Muscular system, tendons, fascia, bursae\n')
w(f"- Muscles: {len(cat('male','muscle'))} (male) / {len(cat('female','muscle'))} (female), tendons {len(cat('male','tendon'))}, tendon sheaths {len(cat('male','tendon sheath'))}, bursae {len(cat('male','bursa'))}, fascia {len(cat('male','fascia'))}, membranes {len(cat('male','membrane'))}.")
w('- Reference: textbooks commonly quote 600–650 skeletal muscles depending on how they are split; there is no single agreed total, so no percentage is claimed.')
w('- Muscle attachment markers in Z-Anatomy (703 male objects) are annotations, not structures, and are excluded.\n')

w('### 3.3 Vessels\n')
w(f"- Arteries: {len(cat('male','artery'))} male / {len(cat('female','artery'))} female. Veins: {len(cat('male','vein'))} / {len(cat('female','vein'))}. Lymph nodes: {len(cat('male','lymph node'))} / {len(cat('female','lymph node'))}, lymphoid organs {len(cat('male','lymphoid'))}, ducts {len(cat('male','duct'))}.")
w('- Named trunk vessels are present (ascending, thoracic and abdominal aorta, superior and inferior vena cava, the cerebral, coronary, limb and visceral branches Z-Anatomy names). The great vessels of the heart are in the core pack from the HRA.')
w('- No agreed reference total for named vessels exists, so none is claimed. Named vessels that Z-Anatomy does not model (many small muscular, cutaneous and perforating branches, most named venous tributaries at the fourth order and below) are missing.')
w('- Capillaries, microvasculature and lymphatic capillaries are out of scope for a gross-anatomy model.\n')

w('### 3.4 Nervous system\n')
w(f"- Nerves {len(cat('male','nerve'))}, plexuses {len(cat('male','plexus'))}, ganglia {len(cat('male','ganglion'))}, meninges {len(cat('male','meninges'))}; brain regions {len(cat('male','brain region'))} (Allen Human Reference Atlas, via HRA).")
w('- **All 12 cranial nerve pairs are present** (I–XII, left and right), checked by the test suite.')
w('- Reference: 31 pairs of spinal nerves. The scans provide the anterior and posterior roots, the cauda equina, the intercostal nerves, the sympathetic trunk, the brachial plexus (roots, trunks, divisions, cords) and the named peripheral nerves of the limbs. **No scan provides the 31 individually named pairs**, so C1–C8, T1–T12, L1–L5, S1–S5 and Co1 (both sides) are supplied as generated schematic tubes (section 3.7), together with the cervical, lumbar and sacral plexuses and the autonomic plexuses. Still missing: most cutaneous branches of the trunk and head, dermatomal rami as separate objects, and the fine autonomic plexuses on individual organs.')
w('- Brain and spinal-cord internal structures from Z-Anatomy (239 male objects) are **excluded**: their provenance inside Z-Anatomy is UW Brainder, which could not be verified. The brain is shown from the HRA/Allen regions instead.')
w('- The spinal cord is the HRA spinal cord (real), replacing the earlier stand-in.\n')

w('### 3.5 Organs, glands, other systems\n')
w(f"- Organ parts from the HRA and Z-Anatomy: digestive {len(cat('male','digestive part'))}, urinary {len(cat('male','urinary part'))}, reproductive {len(cat('male','reproductive part'))} (male) / {len(cat('female','reproductive part'))} (female), heart parts {len(cat('male','heart part'))}, valves {len(cat('male','valve'))}, liver parts {len(cat('male','liver part'))}, bronchi {len(cat('male','bronchus'))}, larynx {len(cat('male','larynx'))}, eye structures {len(cat('male','eye structure'))}, glands {len(cat('male','gland'))}, endocrine {len(cat('male','endocrine'))}.")
w('- Lungs and thyroid are now real meshes (Z-Anatomy lobes; the thyroid gland).')
w('- Excluded because a third-party non-commercial model sits inside Z-Anatomy: **inner ear** (cochlea, vestibule; CC BY-NC-SA 4.0, Univ. of Dundee) and the **Z-Anatomy kidney** (CC BY-NC 4.0). The HRA kidney (CC BY 4.0) is used instead. Consequently the middle-ear ossicles are present but the inner ear is not.')
w('- Heart chambers and valves from Z-Anatomy are skipped so that everything registers to the HRA heart in the core pack.')
w('- Mammary gland (female) is the HRA mammary model.\n')

w('### 3.6 Skin and layers\n')
w('| Layer (peel-away) | Source | Status |\n|---|---|---|\n| 0 Skin (epidermis surface) | HRA skin (core) | real |\n| 1 Dermis | HRA skin surface offset inward 4 mm | **generated, schematic** |\n| 2 Hypodermis / subcutaneous fat | HRA skin offset inward 14 mm, plus real HRA subcutaneous abdominal fat patches (male and female) | shell **generated, schematic**; fat patches real |\n| 3 Deep fascia | Z-Anatomy fasciae | real (51), fitted |\n| 4 Superficial muscles | Z-Anatomy / BodyParts3D | real, fitted |\n| 5 Deep muscles, tendon sheaths, bursae | Z-Anatomy | real, fitted |\n| 6 Skeleton, cartilage, joints | Z-Anatomy | real, fitted |\n')
w('- No open, commercially usable whole-body mesh of epidermis, dermis or hypodermis was found. The two shells are labelled "schematic" in the UI and carry provenance `generated`; they are excluded from every "real anatomy" count.')
w('- The skin has no epidermal sub-layers (stratum corneum … basale) and the model contains no cutaneous nerves or vessels inside the dermis. Nails (8), hair objects (5: eyebrows, eyelashes, pubic hair; scalp hair excluded because it does not fit either skull) are present.\n')

sch = {b: [x for x in counts(b)[1] if str(x.get('category','')).startswith('schematic')] for b in ('male','female')}
w('### 3.7 Schematic stand-ins (generated, not real anatomy)\n')
for b in ('male','female'):
    c = collections.Counter(x['category'] for x in sch[b])
    w(f"- {b.capitalize()}: **{len(sch[b])}** generated structures — " + ', '.join(f"{k.replace('schematic ','')}: {v}" for k, v in sorted(c.items())) + '.')
w('- What they are: 62 spinal nerves (31 pairs), cervical / lumbar / sacral plexuses (both sides), sympathetic ganglia and the lumbar–sacral part of the sympathetic trunk, greater / lesser / least splanchnic, hypogastric and pelvic splanchnic nerves, coeliac, cardiac, superior and inferior hypogastric and oesophageal plexuses, recurrent laryngeal, phrenic and anterior / posterior vagal trunks, the four third molars, and small vessel branches (superior thyroid, lingual, bronchial, suprarenal, middle rectal, vesical, hepatic, cystic, gastric, jejunal, ileal, oesophageal arteries; suprarenal veins; uterine and ovarian vessels or vaginal artery for the female body).')
w('- How they are made: `scripts/assets/build-schematic.ts` builds tubes (6-sided, 1–4 mm radius) and small blobs, positioned from the registered vertebrae, discs, spinal cord, sacrum, rib cage, existing nerves, vessels and organs of the same body. The spinal nerves leave the cord at approximate root levels, pass through the intervertebral level, and end at the plexus or nearest real nerve. Courses are indicative and have not been checked by an anatomist.')
w('- How they are flagged: provenance `generated`, category `schematic …`, name ends "(schematic)", violet colour, a badge on the structure card, the "Schematic" tag in search hits, their own lazy group, and they are excluded from every real-anatomy count.\n')

w('## 4. What Z-Anatomy contains that is not shipped\n')
w('From `build-report.json` (male; female is similar). These are counts of source objects, by reason:\n')
w('| Reason | Objects |\n|---|---:|')
for k, v in sorted(rep['male']['skipped'].items(), key=lambda kv: -kv[1]): w(f'| {k} | {v} |')
w('')
w('## 5. Fit quality (read before calling this "accurate")\n')
w('- The core HRA organs are in one reference frame, so they line up. The Z-Anatomy geometry comes from a different (male) subject and is registered into each HRA body by a global scale and translation, a spine-following displacement, and a per-leg similarity transform (`scripts/assets/extract/register.py`). Residuals: spine ≈ 4 mm RMS; leg landmarks 24–40 mm (male), 8–18 mm (female).')
w('- The **female** body uses the male-derived Z-Anatomy skeleton, muscles, nerves and vessels fitted to the female HRA frame. Sex-specific organs come from the female HRA.')
w('- Fine structures (small nerves, digital vessels) may not sit exactly inside the soft tissue of the fitted body. This has been checked visually only in software-rendered headless Chrome, not by an anatomist.\n')
print('\n'.join(out))
